# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7349d175cfc3578f3abf442b9aad8adc0fe9f52bad01af81c4e7dee87b33b38d6287e39cbc3e11119c941017d8e664f3d1ef5df0dada51f0c2759f9972528d9b

test:
  secret_key_base: 6dac1d45a590cde95f9d8af388551d8bb489f0d8006ff2c96adc4270c6fbb81c41e522fc090ee5276c6356eea830369efe4d5970b2884b9a20ee6832b4cb8111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
